//
//  ItemsListInteractorTests.swift
//  Hero-iOSTest
//
//  Created by inso on 18/12/2018.
//  Copyright (c) 2018 Thomas Moussajee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Hero_iOSTest
import XCTest
import Domain

class ItemsListInteractorTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: ItemsListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupItemsListInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupItemsListInteractor() {
    sut = ItemsListInteractor()
  }
  
  // MARK: Test doubles
  
  class ItemsListPresentationLogicSpy: ItemsListPresentationLogic {
	var presentItemsCalled = XCTestExpectation(description: "ask the presenter to format the result")
	func presentItems(response: ItemsList.GetItems.Response, completion: (ItemsList.GetItems.ViewModel) -> ()) {
		presentItemsCalled.fulfill()
	}
	
	var presentfilterItemsCalled = false
	func filterItems(filter: (Item, Item) -> Bool, viewModel: ItemsList.GetItems.ViewModel, completion: (ItemsList.GetItems.ViewModel) -> ()) {
		presentfilterItemsCalled = true
	}

  }
  
  // MARK: Tests
  
  func testDoGetItems() {
    // Given
    let spy = ItemsListPresentationLogicSpy()
    sut.presenter = spy
	let request = ItemsList.GetItems.Request(page: 0)
    
    // When
	sut.doGetItems(request: request)
	
    // Then
	let result = XCTWaiter().wait(for: [spy.presentItemsCalled], timeout: 10)
	XCTAssertTrue(result == .completed, "doGetItems(request:) should ask the presenter to format the result")
  }
}
