//
//  ItemsListPresenterTests.swift
//  Hero-iOSTest
//
//  Created by inso on 18/12/2018.
//  Copyright (c) 2018 Thomas Moussajee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Hero_iOSTest
import XCTest

class ItemsListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ItemsListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupItemsListPresenter()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupItemsListPresenter() {
    sut = ItemsListPresenter()
  }
  
  // MARK: Test doubles
  
  class ItemsListDisplayLogicSpy: ItemsListDisplayLogic {
    var displayItemsCalled = false
	
	func displayItems(viewModel: ItemsList.GetItems.ViewModel) {
		displayItemsCalled = true
	}
  }
  
  // MARK: Tests
  
  func testPresentItems() {
    // Given
    let spy = ItemsListDisplayLogicSpy()
    sut.viewController = spy
	let response = ItemsList.GetItems.Response(result: [], error: nil)
    
    // When
	sut.presentItems(response: response, completion: { _ in })
    
    // Then
    XCTAssertTrue(spy.displayItemsCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
