//
//  ItemsListModels.swift
//  Hero-iOSTest
//
//  Created by inso on 17/12/2018.
//  Copyright (c) 2018 Thomas Moussajee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain

enum ItemsList
{
	enum GetItems {
		struct Request {
			let page: Int
			
			var dictionaryRepresentation: [String: Any] {
				return [
					"page": page,
				]
			}
		}
		
		struct Response {
			let result: [Item]?
			let error: Error?
		}
		
		struct ViewModel {
			var items: [Item]?
		}
	}
}

