//
//  ItemsListWorker.swift
//  Hero-iOSTest
//
//  Created by inso on 17/12/2018.
//  Copyright (c) 2018 Thomas Moussajee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain

class ItemsListWorker {
	let provider: ItemsUseCase.Type
	
	init(provider: ItemsUseCase.Type) {
		self.provider = provider
	}
	
	func getItems(parameters: [String: Any], completion: @escaping ItemCompletion) {
		provider.getItems(parameters: parameters, completion: completion)
	}
}

