//
//  ItemsListPresenter.swift
//  Hero-iOSTest
//
//  Created by inso on 17/12/2018.
//  Copyright (c) 2018 Thomas Moussajee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain

protocol ItemsListPresentationLogic {
	func presentItems(response: ItemsList.GetItems.Response,
					  completion: (ItemsList.GetItems.ViewModel) -> ())
	func filterItems(filter: (Item, Item) -> Bool,
					 viewModel: ItemsList.GetItems.ViewModel,
					 completion: (ItemsList.GetItems.ViewModel) -> ())
}

class ItemsListPresenter: ItemsListPresentationLogic {
	
	weak var viewController: ItemsListDisplayLogic?
	
	func filterItems(filter: (Item, Item) -> Bool, viewModel: ItemsList.GetItems.ViewModel, completion: (ItemsList.GetItems.ViewModel) -> ()) {
		let newItemOrder = ItemsList.GetItems.ViewModel(items: viewModel.items?.sorted(by: filter))
		completion(newItemOrder)
		viewController?.displayItems(viewModel: newItemOrder)
	}
	
	
	func presentItems(response: ItemsList.GetItems.Response,
					  completion: (ItemsList.GetItems.ViewModel) -> ()) {
		let viewModel = ItemsList.GetItems.ViewModel(items: response.result)
		completion(viewModel)
		viewController?.displayItems(viewModel: viewModel)
	}
}

